modLoader="javafml"
loaderVersion="[40,)"
license="None"
logoFile="banner.png"

[[mods]]
modId="watching"
version="1.3.1"
displayName="From The Fog"
credits="§8Created by §5☆Lunar Eclipse Studios☆"
displayURL="https://lunareclipse.studio/from-the-fog"
issueTrackerURL="https://github.com/LunarEclipseStudios/From-The-Fog/issues"
authors="Bret06"
description='''From The Fog is a Minecraft mod/datapack that adds Herobrine in the most vanilla and spooky way possible.'''

[[dependencies.watching]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20]"
    ordering="NONE"
    side="BOTH"

[[dependencies.watching]]
    modId="watching"
    mandatory=true
    versionRange="[1.3.1]"
    ordering="NONE"
    side="BOTH"



